# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: oncall
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MzUzMTJkOGZkOTc2N2FhMWY4Y2I2YzgxMTA4MmRhNWEyYjY1ZDMyY2VlMDlkMmYwNDE0NjQ2MWE1YzhjZDNjOWYwYzg1M2M1ZGU4N2JhNDYyMWY0NGQ0MjMwMjdhMGE3YTZiMzNlNmM1ODU1YTA0M2IwZmI5NGJmZjkzMDgwZmI=
