package ar.edu.um.isa.oncall.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AccionCorrectivaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccionCorrectivaAllPropertiesEquals(AccionCorrectiva expected, AccionCorrectiva actual) {
        assertAccionCorrectivaAutoGeneratedPropertiesEquals(expected, actual);
        assertAccionCorrectivaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccionCorrectivaAllUpdatablePropertiesEquals(AccionCorrectiva expected, AccionCorrectiva actual) {
        assertAccionCorrectivaUpdatableFieldsEquals(expected, actual);
        assertAccionCorrectivaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccionCorrectivaAutoGeneratedPropertiesEquals(AccionCorrectiva expected, AccionCorrectiva actual) {
        assertThat(actual)
            .as("Verify AccionCorrectiva auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccionCorrectivaUpdatableFieldsEquals(AccionCorrectiva expected, AccionCorrectiva actual) {
        assertThat(actual)
            .as("Verify AccionCorrectiva relevant properties")
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getPrioridad()).as("check prioridad").isEqualTo(expected.getPrioridad()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()))
            .satisfies(a -> assertThat(a.getFechaLimite()).as("check fechaLimite").isEqualTo(expected.getFechaLimite()))
            .satisfies(a -> assertThat(a.getTicketUrl()).as("check ticketUrl").isEqualTo(expected.getTicketUrl()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccionCorrectivaUpdatableRelationshipsEquals(AccionCorrectiva expected, AccionCorrectiva actual) {
        assertThat(actual)
            .as("Verify AccionCorrectiva relationships")
            .satisfies(a -> assertThat(a.getPostmortem()).as("check postmortem").isEqualTo(expected.getPostmortem()));
    }
}
