package ar.edu.um.isa.oncall.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AlertaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlertaAllPropertiesEquals(Alerta expected, Alerta actual) {
        assertAlertaAutoGeneratedPropertiesEquals(expected, actual);
        assertAlertaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlertaAllUpdatablePropertiesEquals(Alerta expected, Alerta actual) {
        assertAlertaUpdatableFieldsEquals(expected, actual);
        assertAlertaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlertaAutoGeneratedPropertiesEquals(Alerta expected, Alerta actual) {
        assertThat(actual)
            .as("Verify Alerta auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlertaUpdatableFieldsEquals(Alerta expected, Alerta actual) {
        assertThat(actual)
            .as("Verify Alerta relevant properties")
            .satisfies(a -> assertThat(a.getFingerprint()).as("check fingerprint").isEqualTo(expected.getFingerprint()))
            .satisfies(a -> assertThat(a.getOrigen()).as("check origen").isEqualTo(expected.getOrigen()))
            .satisfies(a -> assertThat(a.getResumen()).as("check resumen").isEqualTo(expected.getResumen()))
            .satisfies(a -> assertThat(a.getPayload()).as("check payload").isEqualTo(expected.getPayload()))
            .satisfies(a -> assertThat(a.getRecibidaEn()).as("check recibidaEn").isEqualTo(expected.getRecibidaEn()))
            .satisfies(a -> assertThat(a.getProcesada()).as("check procesada").isEqualTo(expected.getProcesada()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlertaUpdatableRelationshipsEquals(Alerta expected, Alerta actual) {
        assertThat(actual)
            .as("Verify Alerta relationships")
            .satisfies(a -> assertThat(a.getServicio()).as("check servicio").isEqualTo(expected.getServicio()))
            .satisfies(a -> assertThat(a.getIncidente()).as("check incidente").isEqualTo(expected.getIncidente()));
    }
}
