package ar.edu.um.isa.oncall.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EventoDeIncidenteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoDeIncidenteAllPropertiesEquals(EventoDeIncidente expected, EventoDeIncidente actual) {
        assertEventoDeIncidenteAutoGeneratedPropertiesEquals(expected, actual);
        assertEventoDeIncidenteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoDeIncidenteAllUpdatablePropertiesEquals(EventoDeIncidente expected, EventoDeIncidente actual) {
        assertEventoDeIncidenteUpdatableFieldsEquals(expected, actual);
        assertEventoDeIncidenteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoDeIncidenteAutoGeneratedPropertiesEquals(EventoDeIncidente expected, EventoDeIncidente actual) {
        assertThat(actual)
            .as("Verify EventoDeIncidente auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoDeIncidenteUpdatableFieldsEquals(EventoDeIncidente expected, EventoDeIncidente actual) {
        assertThat(actual)
            .as("Verify EventoDeIncidente relevant properties")
            .satisfies(a -> assertThat(a.getTipo()).as("check tipo").isEqualTo(expected.getTipo()))
            .satisfies(a -> assertThat(a.getDetalle()).as("check detalle").isEqualTo(expected.getDetalle()))
            .satisfies(a -> assertThat(a.getOcurridoEn()).as("check ocurridoEn").isEqualTo(expected.getOcurridoEn()))
            .satisfies(a -> assertThat(a.getAutomatico()).as("check automatico").isEqualTo(expected.getAutomatico()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoDeIncidenteUpdatableRelationshipsEquals(EventoDeIncidente expected, EventoDeIncidente actual) {
        assertThat(actual)
            .as("Verify EventoDeIncidente relationships")
            .satisfies(a -> assertThat(a.getIncidente()).as("check incidente").isEqualTo(expected.getIncidente()));
    }
}
