package ar.edu.um.isa.oncall.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IncidenteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncidenteAllPropertiesEquals(Incidente expected, Incidente actual) {
        assertIncidenteAutoGeneratedPropertiesEquals(expected, actual);
        assertIncidenteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncidenteAllUpdatablePropertiesEquals(Incidente expected, Incidente actual) {
        assertIncidenteUpdatableFieldsEquals(expected, actual);
        assertIncidenteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncidenteAutoGeneratedPropertiesEquals(Incidente expected, Incidente actual) {
        assertThat(actual)
            .as("Verify Incidente auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncidenteUpdatableFieldsEquals(Incidente expected, Incidente actual) {
        assertThat(actual)
            .as("Verify Incidente relevant properties")
            .satisfies(a -> assertThat(a.getTitulo()).as("check titulo").isEqualTo(expected.getTitulo()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getSeveridad()).as("check severidad").isEqualTo(expected.getSeveridad()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()))
            .satisfies(a -> assertThat(a.getDetectadoEn()).as("check detectadoEn").isEqualTo(expected.getDetectadoEn()))
            .satisfies(a -> assertThat(a.getReconocidoEn()).as("check reconocidoEn").isEqualTo(expected.getReconocidoEn()))
            .satisfies(a -> assertThat(a.getMitigadoEn()).as("check mitigadoEn").isEqualTo(expected.getMitigadoEn()))
            .satisfies(a -> assertThat(a.getResueltoEn()).as("check resueltoEn").isEqualTo(expected.getResueltoEn()))
            .satisfies(a -> assertThat(a.getUsuariosAfectados()).as("check usuariosAfectados").isEqualTo(expected.getUsuariosAfectados()))
            .satisfies(a -> assertThat(a.getCumplioObjetivo()).as("check cumplioObjetivo").isEqualTo(expected.getCumplioObjetivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncidenteUpdatableRelationshipsEquals(Incidente expected, Incidente actual) {
        assertThat(actual)
            .as("Verify Incidente relationships")
            .satisfies(a -> assertThat(a.getServicios()).as("check servicios").isEqualTo(expected.getServicios()));
    }
}
