package ar.edu.um.isa.oncall.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NotificacionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificacionAllPropertiesEquals(Notificacion expected, Notificacion actual) {
        assertNotificacionAutoGeneratedPropertiesEquals(expected, actual);
        assertNotificacionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificacionAllUpdatablePropertiesEquals(Notificacion expected, Notificacion actual) {
        assertNotificacionUpdatableFieldsEquals(expected, actual);
        assertNotificacionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificacionAutoGeneratedPropertiesEquals(Notificacion expected, Notificacion actual) {
        assertThat(actual)
            .as("Verify Notificacion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificacionUpdatableFieldsEquals(Notificacion expected, Notificacion actual) {
        assertThat(actual)
            .as("Verify Notificacion relevant properties")
            .satisfies(a -> assertThat(a.getCanal()).as("check canal").isEqualTo(expected.getCanal()))
            .satisfies(a -> assertThat(a.getDestino()).as("check destino").isEqualTo(expected.getDestino()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()))
            .satisfies(a -> assertThat(a.getEnviadaEn()).as("check enviadaEn").isEqualTo(expected.getEnviadaEn()))
            .satisfies(a -> assertThat(a.getIntentos()).as("check intentos").isEqualTo(expected.getIntentos()))
            .satisfies(a -> assertThat(a.getErrorMensaje()).as("check errorMensaje").isEqualTo(expected.getErrorMensaje()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificacionUpdatableRelationshipsEquals(Notificacion expected, Notificacion actual) {
        assertThat(actual)
            .as("Verify Notificacion relationships")
            .satisfies(a -> assertThat(a.getIncidente()).as("check incidente").isEqualTo(expected.getIncidente()));
    }
}
