package ar.edu.um.isa.oncall.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ObjetivoDeServicioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertObjetivoDeServicioAllPropertiesEquals(ObjetivoDeServicio expected, ObjetivoDeServicio actual) {
        assertObjetivoDeServicioAutoGeneratedPropertiesEquals(expected, actual);
        assertObjetivoDeServicioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertObjetivoDeServicioAllUpdatablePropertiesEquals(ObjetivoDeServicio expected, ObjetivoDeServicio actual) {
        assertObjetivoDeServicioUpdatableFieldsEquals(expected, actual);
        assertObjetivoDeServicioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertObjetivoDeServicioAutoGeneratedPropertiesEquals(ObjetivoDeServicio expected, ObjetivoDeServicio actual) {
        assertThat(actual)
            .as("Verify ObjetivoDeServicio auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertObjetivoDeServicioUpdatableFieldsEquals(ObjetivoDeServicio expected, ObjetivoDeServicio actual) {
        assertThat(actual)
            .as("Verify ObjetivoDeServicio relevant properties")
            .satisfies(a -> assertThat(a.getTipo()).as("check tipo").isEqualTo(expected.getTipo()))
            .satisfies(a ->
                assertThat(a.getSeveridadAplicable()).as("check severidadAplicable").isEqualTo(expected.getSeveridadAplicable())
            )
            .satisfies(a -> assertThat(a.getMinutosObjetivo()).as("check minutosObjetivo").isEqualTo(expected.getMinutosObjetivo()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertObjetivoDeServicioUpdatableRelationshipsEquals(ObjetivoDeServicio expected, ObjetivoDeServicio actual) {
        assertThat(actual)
            .as("Verify ObjetivoDeServicio relationships")
            .satisfies(a -> assertThat(a.getServicio()).as("check servicio").isEqualTo(expected.getServicio()));
    }
}
