package ar.edu.um.isa.oncall.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PasoEscalamientoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPasoEscalamientoAllPropertiesEquals(PasoEscalamiento expected, PasoEscalamiento actual) {
        assertPasoEscalamientoAutoGeneratedPropertiesEquals(expected, actual);
        assertPasoEscalamientoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPasoEscalamientoAllUpdatablePropertiesEquals(PasoEscalamiento expected, PasoEscalamiento actual) {
        assertPasoEscalamientoUpdatableFieldsEquals(expected, actual);
        assertPasoEscalamientoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPasoEscalamientoAutoGeneratedPropertiesEquals(PasoEscalamiento expected, PasoEscalamiento actual) {
        assertThat(actual)
            .as("Verify PasoEscalamiento auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPasoEscalamientoUpdatableFieldsEquals(PasoEscalamiento expected, PasoEscalamiento actual) {
        assertThat(actual)
            .as("Verify PasoEscalamiento relevant properties")
            .satisfies(a -> assertThat(a.getOrden()).as("check orden").isEqualTo(expected.getOrden()))
            .satisfies(a -> assertThat(a.getEsperaMinutos()).as("check esperaMinutos").isEqualTo(expected.getEsperaMinutos()))
            .satisfies(a -> assertThat(a.getCanal()).as("check canal").isEqualTo(expected.getCanal()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPasoEscalamientoUpdatableRelationshipsEquals(PasoEscalamiento expected, PasoEscalamiento actual) {
        assertThat(actual)
            .as("Verify PasoEscalamiento relationships")
            .satisfies(a -> assertThat(a.getPolitica()).as("check politica").isEqualTo(expected.getPolitica()))
            .satisfies(a -> assertThat(a.getRotacion()).as("check rotacion").isEqualTo(expected.getRotacion()));
    }
}
