package ar.edu.um.isa.oncall.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PoliticaEscalamientoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPoliticaEscalamientoAllPropertiesEquals(PoliticaEscalamiento expected, PoliticaEscalamiento actual) {
        assertPoliticaEscalamientoAutoGeneratedPropertiesEquals(expected, actual);
        assertPoliticaEscalamientoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPoliticaEscalamientoAllUpdatablePropertiesEquals(PoliticaEscalamiento expected, PoliticaEscalamiento actual) {
        assertPoliticaEscalamientoUpdatableFieldsEquals(expected, actual);
        assertPoliticaEscalamientoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPoliticaEscalamientoAutoGeneratedPropertiesEquals(PoliticaEscalamiento expected, PoliticaEscalamiento actual) {
        assertThat(actual)
            .as("Verify PoliticaEscalamiento auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPoliticaEscalamientoUpdatableFieldsEquals(PoliticaEscalamiento expected, PoliticaEscalamiento actual) {
        assertThat(actual)
            .as("Verify PoliticaEscalamiento relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getRepetirVeces()).as("check repetirVeces").isEqualTo(expected.getRepetirVeces()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPoliticaEscalamientoUpdatableRelationshipsEquals(PoliticaEscalamiento expected, PoliticaEscalamiento actual) {
        assertThat(actual)
            .as("Verify PoliticaEscalamiento relationships")
            .satisfies(a -> assertThat(a.getServicio()).as("check servicio").isEqualTo(expected.getServicio()));
    }
}
