package ar.edu.um.isa.oncall.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PostmortemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostmortemAllPropertiesEquals(Postmortem expected, Postmortem actual) {
        assertPostmortemAutoGeneratedPropertiesEquals(expected, actual);
        assertPostmortemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostmortemAllUpdatablePropertiesEquals(Postmortem expected, Postmortem actual) {
        assertPostmortemUpdatableFieldsEquals(expected, actual);
        assertPostmortemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostmortemAutoGeneratedPropertiesEquals(Postmortem expected, Postmortem actual) {
        assertThat(actual)
            .as("Verify Postmortem auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostmortemUpdatableFieldsEquals(Postmortem expected, Postmortem actual) {
        assertThat(actual)
            .as("Verify Postmortem relevant properties")
            .satisfies(a -> assertThat(a.getTitulo()).as("check titulo").isEqualTo(expected.getTitulo()))
            .satisfies(a -> assertThat(a.getResumen()).as("check resumen").isEqualTo(expected.getResumen()))
            .satisfies(a -> assertThat(a.getCausaRaiz()).as("check causaRaiz").isEqualTo(expected.getCausaRaiz()))
            .satisfies(a -> assertThat(a.getLineaDeTiempo()).as("check lineaDeTiempo").isEqualTo(expected.getLineaDeTiempo()))
            .satisfies(a ->
                assertThat(a.getLeccionesAprendidas()).as("check leccionesAprendidas").isEqualTo(expected.getLeccionesAprendidas())
            )
            .satisfies(a -> assertThat(a.getPublicado()).as("check publicado").isEqualTo(expected.getPublicado()))
            .satisfies(a -> assertThat(a.getPublicadoEn()).as("check publicadoEn").isEqualTo(expected.getPublicadoEn()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostmortemUpdatableRelationshipsEquals(Postmortem expected, Postmortem actual) {
        assertThat(actual)
            .as("Verify Postmortem relationships")
            .satisfies(a -> assertThat(a.getIncidente()).as("check incidente").isEqualTo(expected.getIncidente()));
    }
}
