package ar.edu.um.isa.oncall.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RotacionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRotacionAllPropertiesEquals(Rotacion expected, Rotacion actual) {
        assertRotacionAutoGeneratedPropertiesEquals(expected, actual);
        assertRotacionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRotacionAllUpdatablePropertiesEquals(Rotacion expected, Rotacion actual) {
        assertRotacionUpdatableFieldsEquals(expected, actual);
        assertRotacionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRotacionAutoGeneratedPropertiesEquals(Rotacion expected, Rotacion actual) {
        assertThat(actual)
            .as("Verify Rotacion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRotacionUpdatableFieldsEquals(Rotacion expected, Rotacion actual) {
        assertThat(actual)
            .as("Verify Rotacion relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getTipo()).as("check tipo").isEqualTo(expected.getTipo()))
            .satisfies(a -> assertThat(a.getZonaHoraria()).as("check zonaHoraria").isEqualTo(expected.getZonaHoraria()))
            .satisfies(a -> assertThat(a.getActiva()).as("check activa").isEqualTo(expected.getActiva()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRotacionUpdatableRelationshipsEquals(Rotacion expected, Rotacion actual) {
        assertThat(actual)
            .as("Verify Rotacion relationships")
            .satisfies(a -> assertThat(a.getEquipo()).as("check equipo").isEqualTo(expected.getEquipo()));
    }
}
