package ar.edu.um.isa.oncall.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TurnoDeGuardiaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTurnoDeGuardiaAllPropertiesEquals(TurnoDeGuardia expected, TurnoDeGuardia actual) {
        assertTurnoDeGuardiaAutoGeneratedPropertiesEquals(expected, actual);
        assertTurnoDeGuardiaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTurnoDeGuardiaAllUpdatablePropertiesEquals(TurnoDeGuardia expected, TurnoDeGuardia actual) {
        assertTurnoDeGuardiaUpdatableFieldsEquals(expected, actual);
        assertTurnoDeGuardiaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTurnoDeGuardiaAutoGeneratedPropertiesEquals(TurnoDeGuardia expected, TurnoDeGuardia actual) {
        assertThat(actual)
            .as("Verify TurnoDeGuardia auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTurnoDeGuardiaUpdatableFieldsEquals(TurnoDeGuardia expected, TurnoDeGuardia actual) {
        assertThat(actual)
            .as("Verify TurnoDeGuardia relevant properties")
            .satisfies(a -> assertThat(a.getDesde()).as("check desde").isEqualTo(expected.getDesde()))
            .satisfies(a -> assertThat(a.getHasta()).as("check hasta").isEqualTo(expected.getHasta()))
            .satisfies(a -> assertThat(a.getEsReemplazo()).as("check esReemplazo").isEqualTo(expected.getEsReemplazo()))
            .satisfies(a -> assertThat(a.getNota()).as("check nota").isEqualTo(expected.getNota()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTurnoDeGuardiaUpdatableRelationshipsEquals(TurnoDeGuardia expected, TurnoDeGuardia actual) {
        assertThat(actual)
            .as("Verify TurnoDeGuardia relationships")
            .satisfies(a -> assertThat(a.getRotacion()).as("check rotacion").isEqualTo(expected.getRotacion()));
    }
}
