export enum TipoEvento {
  CREACION = 'CREACION',

  ASIGNACION = 'ASIGNACION',

  ESCALAMIENTO = 'ESCALAMIENTO',

  NOTA = 'NOTA',

  CAMBIO_DE_ESTADO = 'CAMBIO_DE_ESTADO',

  RESOLUCION = 'RESOLUCION',
}
